# Generated by Django 3.2.6 on 2021-09-25 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grabezy_app', '0002_auto_20210925_1808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Electronics',
            new_name='Electronic',
        ),
    ]
