# Generated by Django 3.2.6 on 2021-09-25 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grabezy_app', '0003_rename_electronics_electronic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electronic',
            old_name='catagory',
            new_name='subcatagory',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='catagory',
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='catagory',
        ),
    ]
