# Generated by Django 3.2.6 on 2021-09-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grabezy_app', '0004_auto_20210925_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electronic',
            old_name='subcatagory',
            new_name='catagory',
        ),
        migrations.RenameField(
            model_name='fashion',
            old_name='subcatagory',
            new_name='catagory',
        ),
        migrations.RenameField(
            model_name='grocery',
            old_name='subcatagory',
            new_name='catagory',
        ),
    ]
