# Generated by Django 3.2.6 on 2021-10-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabezy_app', '0005_auto_20210925_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=20)),
                ('isssue', models.TextField()),
            ],
        ),
    ]
