# Generated by Django 3.2.6 on 2021-10-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabezy_app', '0008_order_orderupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=''),
        ),
    ]
