# Generated by Django 3.2.6 on 2021-10-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabezy_app', '0009_alter_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
